### PR TITLE
New Logo For KIWIX

### PR DESCRIPTION
**Pull request by DhairyaBahl**
I have changed the logo file and added new file with the same name in the .png format by converting the .svg file to .png file using the Adobe Illustrator and exchanged this with the previous one. I guess this should solve the issue. This file exchange also lead to size reduction by few KBs.

Kindly guide me further if issue is still unresolved.

Thanks :)

### CODE REVIEW

**Comment by rgaudin** [comment]
The new file has different dimensions ; why is that?
Content position is now different (more margins) ; is that what we want? Can we check how it looks like?

**Comment by rgaudin** [comment]
Hum, now #530 has a different logo than this *new* one.
I've also launched a build so you have the various packages available:
- [linux](http://tmp.kiwix.org/ci/kiwix-hotspot-linux-logo.tar.gz)
- [macos](http://tmp.kiwix.org/ci/kiwix-hotspot-macos-logo.dmg)
- [win](http://tmp.kiwix.org/ci/kiwix-hotspot-win32-logo.exe)

**Once the correct logo to use is settled**, we should have screenshot of icons in all platform to check that it looks correct before we can merge it.

**Comment by DhairyaBahl** [comment]
@rgaudin @popolechein  I changed the image again as per given in the issue #530 . But somehow I am unable to build it in my windows pc. I was having few errors. Kindly tell me what to do ?

Thanks :)

**Comment by rgaudin** [comment]
@DhairyaBahl you don't have to launch the process, we just want to check the installer's icon (both its file on the explorer and taskbar) and in the about window.
Now you've used the macos version ; I don't think it would fit the linux and windows versions but that's for @Popolechien to tell.
I'll relaunch a build with this so you can make screenshots with this version.

Please note that there is also a `kiwix-hotspot-logo.icns` and `kiwix-hotspot-logo.ico` files to change as well.

**Comment by DhairyaBahl** [comment]
@rgaudin Yes, I was also having the thought on changing the icons but i only have .png file of the image. So I think i have to convert it to .ico or whtever extension that is . Right ? Thanks :)

**Comment by DhairyaBahl** [comment]
@rgaudin I also updated the .ico and .icns files. Now working on the windows and linux images :)

**Comment by rgaudin** [comment]
Yes I think so, that's used inside the hotspot but uses old branding as well

**Comment by DhairyaBahl** [comment]
@rgaudin 
I also updated the favicon.png in proper size. Can you tell me how to make the image suitable for windows and linux as well. 
I am stuck ? Thanks :)

**Comment by Popolechien** [comment]
@rgaudin things look like they are going smoothly, but from what I read do I need to provide more input?
To summarize things from #530, here's the desired app logo/icon (remove the `2` at the bottom, eh)
image
And this one is the app desktop **button** for macOS (from the zip file on #530; icon and app logo remain as above):
Kiwix-Icon-MacOS-installer-(512px-├ù-512px-@1x)

**Comment by DhairyaBahl** [comment]
@Popolechien Can you please tell me what I have to do next ? @rgaudin was saying i still have to fix for windows and linux !!
Kindly Guide me further. Thanks :)

Thanks :)

**Comment by Popolechien** [comment]
@DhairyaBahl - as indicated above: the (first) transparent logo everywhere (app file, icon, etc.) with **one** exception: the round button (second one above), only for the macOS desktop button.

**Comment by DhairyaBahl** [comment]
@Popolechien Okay Got it. Yesterday I applied the MAC logo everywhere in the repo. I will work on it again.

Thanks :)

**Pull request closed without merging**
