### PR TITLE
Added English Installer Usage Guide

### PR DESCRIPTION
**Pull request by alicenichols**
NB:
- There are some images that need English equivalents (e.g. page 9)
- Have used British English, can be modified to AE if needed

### CODE REVIEW

**Comment by rgaudin** [comment]
Great !
@kelson42 please don't merge this PR in once OK as github is not upstream. Either push it to framagit or let me know and I'll do it.

**Comment by kelson42** [comment]
@rgaudin Yes, please go ahead with the PR review/merge however you want.

**Comment by rgaudin** [comment]
Merged [on framagit](https://framagit.org/ideascube/kiwix-hotspot/commit/4eecd86c5ce2c956d26011c9af8ebfe2bf37eb9a). Also fixed typo in FR. Thanks !

**Comment by kelson42** [comment]
@alicenichols Thank you very much for your help, you file has finally landed in the repo here https://framagit.org/ideascube/kiwix-hotspot/blob/master/docs/Kiwix%20Hotspot%20Installer%20EN.docx

**Pull request closed without merging**
